# Use DecapBridge auth (required)
backend:
  name: git-gateway
  repo: dangeol/ilkh-website
  branch: main
  identity_url: https://auth.decapbridge.com/sites/4fda528a-888b-4750-a948-ca8a6713359b
  gateway_url: https://gateway.decapbridge.com

  # Quickly see who did what (optional)
  commit_messages:
    create: Create {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    update: Update {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    delete: Delete {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    uploadMedia: Upload “{{path}}” - {{author-name}} <{{author-login}}> via DecapBridge
    deleteMedia: Delete “{{path}}” - {{author-name}} <{{author-login}}> via DecapBridge
    openAuthoring: Message {{message}} - {{author-name}} <{{author-login}}> via DecapBridge

# Better Decap + Bridge logo (optional)
logo_url: https://decapbridge.com/decapcms-with-bridge.svg

# Add site links in DecapCMS (optional)
site_url: https://inros-lackner.com.kh

# Required media settings
media_folder: "../../public/images"
public_folder: "/images"

media_library:
  name: uploadcare # "uploadcare" or "cloudinary" or leave it as "simple"

collections:
  - name: "competencies"
    label: "Competencies"
    folder: "content/competencies"
    create: true
    slug: "{{slug}}"
    summary: "{{fields.title}}"
    media_folder: "../../public/images/competencies/{{slug}}"
    public_folder: "/images/competencies/{{slug}}"
    fields:
      - { name: "title", label: "Competency Name", widget: "string", required: true }
      - { name: "value", label: "Value (Slug or Key)", widget: "string", required: true }
      - { name: "order", label: "Order No.", widget: "number", value_type: "int", required: true }
      - { name: "subline", label: "Subline", widget: "string", required: true }
      - { name: "icon", label: "Icon", widget: "image", required: true }
      - { name: "image", label: "Image", widget: "image", required: true }
      - { name: "body", label: "Description", widget: "markdown", required: true }

  - name: "service-clusters"
    label: "Service Clusters"
    folder: "content/service-clusters"
    create: true
    slug: "{{slug}}"
    summary: "{{fields.title}}"
    media_folder: "../../public/images/service-clusters/{{slug}}"
    public_folder: "/images/service-clusters/{{slug}}"
    fields:
      - { name: "title", label: "Cluster Name", widget: "string", required: true }
      - { name: "value", label: "Value (Slug or Key)", widget: "string", required: true }
      - { name: "order", label: "Order No.", widget: "number", value_type: "int", required: true }
      - { name: "subline", label: "Subline", widget: "string", required: true }
      - { name: "icon", label: "Icon", widget: "image", required: false }
      - { name: "image", label: "Image", widget: "image", required: true }
      - { name: "body", label: "Description", widget: "markdown", required: true }

  - name: "services"
    label: "Services"
    folder: "content/services"
    create: true
    slug: "{{slug}}"
    summary: "{{fields.title}}"
    media_folder: "../../public/images/services/{{slug}}"
    public_folder: "/images/services/{{slug}}"
    fields:
      - { name: "title", label: "Service Name", widget: "string", required: true }
      - { name: "value", label: "Value (Slug or Key)", widget: "string", required: true }
      - { name: "body", label: "Description", widget: "markdown", required: true }

  - name: "projects"
    label: "Projects"
    folder: "content/projects"
    create: true
    slug: "{{slug}}"
    summary: "{{fields.title}}"
    media_folder: "../../public/images/projects/{{slug}}"
    public_folder: "/images/projects/{{slug}}"
    fields:
      - { name: "title", label: "Project Title", widget: "string", required: true }
      - name: "competency"
        label: "Competency"
        widget: "relation"
        collection: "competencies"
        search_fields: ["title"]
        value_field: "value"
        display_fields: ["title"]
        required: true
      - name: "serviceCluster"
        label: "Service Cluster"
        widget: "relation"
        collection: "service-clusters"
        search_fields: ["title"]
        value_field: "value"
        display_fields: ["title"]
        required: true
      - {
          name: "thumbnail",
          label: "Thumbnail Image",
          widget: "image",
          required: true,
        }
      - name: "gallery"
        label: "Gallery Images"
        widget: "list"
        fields:
          - name: "image"
            label: "Image"
            widget: "image"
      - { name: "isShowcase", label: "Showcase Project?", widget: "boolean", default: false }
      - { name: "dateStart", label: "Start Date", widget: "datetime", required: true }
      - { name: "dateEnd", label: "End Date", widget: "datetime", required: false }
      - { name: "summary", label: "Summary", widget: "string", required: true }
      - { name: "body", label: "Description", widget: "markdown", required: true }