# Use DecapBridge auth (required)
backend:
  name: git-gateway
  repo: dangeol/ilkh-website
  branch: main
  identity_url: https://auth.decapbridge.com/sites/4fda528a-888b-4750-a948-ca8a6713359b
  gateway_url: https://gateway.decapbridge.com

  # Quickly see who did what (optional)
  commit_messages:
    create: Create {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    update: Update {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    delete: Delete {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    uploadMedia: Upload “{{path}}” - {{author-name}} <{{author-login}}> via DecapBridge
    deleteMedia: Delete “{{path}}” - {{author-name}} <{{author-login}}> via DecapBridge
    openAuthoring: Message {{message}} - {{author-name}} <{{author-login}}> via DecapBridge

# Better Decap + Bridge logo (optional)
logo_url: https://decapbridge.com/decapcms-with-bridge.svg

# Add site links in DecapCMS (optional)
site_url: https://inros-lackner.com.kh

media_folder: "public/images/projects/{{slug}}"
public_folder: "/images/projects/{{slug}}"

collections:
  - name: "projects"
    label: "Projects"
    folder: "content/projects"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Project Title", widget: "string", required: true }
      - {
          name: "category",
          label: "Category",
          widget: "select",
          options: [
            { label: "Integrated Building Design", value: "integrated-building-design" },
            { label: "Infrastructure & Environment", value: "infrastructure-and-environment" },
            { label: "Structural Engineering & Building Assessment", value: "structural-engineering-and-building-assessment" },
            { label: "Geotechnical Engineering", value: "geotechnical-engineering" },
            { label: "Project Management & Construction Supervision", value: "project-management-and-construction-supervision" },
            { label: "Surveying & Geo-Information Systems", value: "surveying-and-geo-information-systems" }
          ]
        }
      - {
          name: "thumbnail",
          label: "Thumbnail Image",
          widget: "image",
          required: true,
        }
      - name: "gallery"
        label: "Gallery Images"
        widget: "list"
        fields:
          - name: "image"
            label: "Image"
            widget: "image"
      - { name: "isShowcase", label: "Showcase Project?", widget: "boolean", default: false }
      - { name: "dateStart", label: "Start Date", widget: "date", required: true }
      - { name: "dateEnd", label: "End Date", widget: "date", required: false }
      - { name: "summary", label: "Summary", widget: "string", required: true }
      - { name: "body", label: "Project Description", widget: "markdown", required: true }

